 - name : "Testing Filter"
   hosts : localhost
   vars_prompt :
     - name : number
       prompt : "Please Enter Number"
       private : false
   tasks :
    - name : "Checking LessThan"
      ansible.builtin.debug : 
        msg : "The Number Is {{number}}"
    - name : "LessThan 10"
      ansible.builtin.debug :
        msg : "The Entered Number Is LessThan 10"
      when : {{number}}  < 10
    
    - name : "Checking GreaterThan Or Equal"
      ansible.builtin.debug :
        msg : "The Entered Number Is Greater Than Or Equal 10"
      when : {{number}} > 10