- name : "Converting Lower To Upper"
  hosts : localhost
  vars :
    greeting : "Welcome To World"
  tasks :
    - name : "Printing Converted Upper"
      ansible.builtin.debug:
       msg : "Before Converted {{greeting}}, After Converted {{greeting | upper}} "
