- name : "Student Details"
  hosts : localhost
  vars_prompt :
    - name : STUNAME
      prompt : "Please Enter The Student Name :"
      private : false

    - name : STUCLASS
      prompt : "Please Enter Student Class :"
      private : false

    - name : STUPERCENTAGE
      prompt : "Please Enter Student Percentage :"
      private : false

  tasks :
    - name : "Printing Student Details : "
      ansible.builtin.debug:
       msg : "Student Details Are {{STUNAME}} {{STUCLASS}} {{STUPERCENTAGE}}"
