- name : "Min And Max Ages"
  hosts : localhost
  vars :
   number : [2,5,6,9,10]
  tasks :
   - name : "Minimum Number"
     ansible.builtin.debug :
       msg : "Minimum Number Is {{number | min}}, Maximum Number Is {{number | max}} "