- name : "List To Dict"
  hosts : localhost
  vars :
    mylist : 
      - key : "MANGO"
        value : "400$"
      - key : "APPLE"
        value : "500$"
  tasks :
    - name : Print Dict
      ansible.builtin.debug:
       msg : "Before Convert {{mylist}},After Convert {{mylist | items2dict}}"