- name : "Prefernece Check"
  hosts: demo
  vars : 
   WISH: "PLAY LEVEL"
  vars_files:
   - file1.yaml
  vars_prompt:
    - name : WISH
      prompt: "PLEASE ENETER"
      private : false
    
  tasks :
   - name : "Printing"
    #  vars :
    #   WISH: "TASK LEVEL"
     ansible.builtin.debug:
      msg : "{{WISH}}"
 