  - name : "Backend Server Configuration"
    hosts : backend
    become : yes
    tasks :
      - name : "Disable default nodejs version"
        ansible.builtin.command : dnf module disable nodejs -y
      
      - name : "Enable required nodejs version"
        ansible.builtin.command : dnf module enable nodejs:20 -y
      
      - name : "Install nodejs"
        ansible.builtin.dnf :
         name : nodejs
         state : installed

      - name : "Creating user for service run"
        ansible.builtin.user : 
         name : expense

      - name : "Creating seperate folder for code"
        ansible.builtin.file:
         path: /app
         state : directory
