  - name : "Backend Server Configuration"
    hosts : backend
    become : yes
    tasks :
      - name : "Disable default nodejs version"
        ansible.builtin.command : dnf module disable nodejs -y
      
      - name : "Enable required nodejs version"
        ansible.builtin.command : dnf module enable nodejs:20 -y
      
      - name : "Install nodejs"
        ansible.builtin.dnf :
         name : "{{item}}"
         state : installed
        loop :
         - nodejs
         - mysql

      - name : "Creating user for service run"
        ansible.builtin.user : 
         name : expense

      - name : "Creating seperate folder for code"
        ansible.builtin.file:
         path : /app
         state : directory
      
      - name : "Downloading Code"
        ansible.builtin.get_url :
          url : https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
          dest: /tmp/backend.zip

      - name : "Unzip above code into app folder"
        ansible.builtin.unarchive :
         src : /tmp/backend.zip
         dest : /app
         remote_src: yes

      - name : "Install Dependencies For App"
        ansible.builtin.command : npm install 
        args :
         chdir : /app
      
      - name : "Copy Backend Service File To Remote"
        ansible.builtin.copy :
         src : backend.service
         dest : /etc/systemd/system/backend.service

      - name : "Install PyMysql To connect MySqlServer From Ansible"
        ansible.builtin.pip:
         name : PyMySQL
         exceutable : pip3.9
      
      - name : "Connect DB Serevr and Import Data"
        community.mysql.mysql_db :
         login_user : root
         login_password : ExpenseApp@1
         login_host : 172.31.30.80
         target : /app/schema/backend.sql
         state : import
         name : all

      - name : "Reload Daemon For Systemd"
        ansible.builtin.systemd_service
         daemon_reload: true
        
      - name : "Start Backend Service"
         ansible.builtin.systemd_service:
           name : backend
           state : started
           enable : true

      
     