- name : "Conditions Check"
  hosts : localhost
  tasks :
   - name : "Checking User Exit Or Not"
     ansible.builtin.command: id TestUser
      ignore-errors: true
    
   - name : "Print Test Message"
     ansible.builtin.debug:
       msg: "Tested.."
      