- name : "Conditions Check"
  hosts : localhost
  tasks :
   - name : "Checking User Exit Or Not"
     ansible.builtin.command: id TestUser
     register: USER
     ignore_errors: true
   - name : User Exists
     ansible.builtin.debug:
       msg : "User Exists"
       when : USER.rc != 1
       
   - name : "Print Test Message"
     ansible.builtin.debug:
       msg: "User Info : {{USER}}"
      