---
- name: DB Configuration
  hosts: DB
  become: yes
  vars_prompt:
    - name: RootPass
      prompt: Please Enter Root Password
      private: no
  tasks:
    - name: Installing MySql Server
      ansible.builtin.dnf:
        name: mysql-server
        state: latest
    - name: Start mysqld Service
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: yes
    - name: Installing Python Dependencies For SQL
      ansible.builtin.pip:
        name:
          - PyMySql
          - cryptography
        executable: pip3.9
    - name: Check DB Connection
      community.mysql.mysql_info:
        login_user: root
        login_password: "{{RootPass}}"
        filter: version
      ignore_errors: yes
      register: sqlconn
    - name: Set Root Password
      ansible.builtin.command: mysql_secure_installation --set-root-pass {{RootPass}}
      when: sqlconn.changed is false
