- name : "Installing Packages"
  hosts : localhost
  tasks :
   - name : "Installing Packages In localhost"
     ansible.builtin.dnf:
      name : "{{item.name}}"
      state : "{{item.state}}"
     loop :
      - { "name":"nginx","state":"installed" } 
      - { "name":"postfix","state":"installed" } 
      - { "name":"mysql-server","state":"installed" } 
