- name : "Configuring DB"
  hosts : localhost
  tasks  :
    - name : "Checking mysql-server Is Installed"
      ansible.builtin.command : dnf installed list | grep mysql-server
      register: mysqlstatus

    - name : "Print Status"
      ansible.builtin.debug :
       msg : "{{mysqlstatus}}"