- name : "Configuring DB"
  hosts : localhost
  tasks  :
    - name : "Checking mysql-server Is Installed"
      ansible.builtin.command : dnf list installed | grep mysql-server
      register: mysqlstatus

    - name : "Print Status"
      ansible.builtin.debug :
       msg : "done"
      when : "'mysql-server' in mysqlstatus.stdout_lines"