- name : "Make DB Configuration"
  hosts : localhost
  tasks :
   - name : "Gather Package Details"
     ansible.builtin.package_facts:
     register : facts

   - name : "Checking mysql-server Installed"
     ansible.builtin.debug:
       msg : "Already Mysql-server Installed"
     when : "'mysql' in facts"
     
   - name : "Checking mysql-server Not Installed"
     ansible.builtin.debug:
       msg : "Mysql-server Is Not Installed"
     when : "'mysql' not in facts[0:5]"

   - name : "Checking mysql-server Not Installed"
     ansible.builtin.dnf:
        name : "mysql-server"
        state : "installed"
     when : "'mysql' not in facts[0:5]"