- name : "Removing Packages"
  hosts : localhost
  tasks :
   - name : "Removing Packages From localhost"
     ansible.builtin.dnf:
      name : "{{item.name}}"
      state : "{{item.state}}"
     loop :
      - {"name":"nginx","state":"absent"}
      - {"name":"postfix","state":"absent"}
      - {"name":"mysql-server","state":"absent"}
      