- name : Variables
  hosts : localhost
  vars : 
     name : "HELLO HANUMAIAH"
     message : "WELCOME TO WORLD"
  tasks :
   - name : printing variables
     ansible.builtin.debug:
       msg : "{{name}},{{message}}"